let wordList1 = [
    "stuck up",
    "playful",
    "open minded",
    "bohemian",
    "emo",
    "adventurous",
    "arrogant",
    "depressed",
    "tender",
    "loving",
    "stoic",
    "cute",
    "cruel",
    "demure",
    "sadistic",
    "masochistic",
    "lonely",
    "promiscuous",
    "horny",
    "kinky",
    "mischievous",
    "benevolent",
    "enthusiastic",
    "greedy",
    "needy",
    "bored",
    "stressed",
    "nerdy",
    "geeky",
    "wise",
    "sophisticated",
    "aggressive",
    "stuffy",
    "conservative",
    "strong",
    "vain",
    "narcissistic",
    "obsessive",
    "rich",
    "poor",
    "imaginative",
    "intoxicated",
    "incapacitated",
    "curious",
    "androgynous",
    "fabulous",
    "outgoing",
    "introvert",
    "self-conscious",
    "cocky",
    "bullying",
    "muscular",
    "sex-positive",
    "deeply embarrassed",
    "blushing",
    "flustered",
    "expressive",
    "handsome",
    "frightening",
    "authoritarian",
    "fainting",
    "exhausted",
    "sleepy",
    "drugged",
    "ecstatic",
    "married",
    "confused"
];

let wordList2 = [
    "hipster",
    "officer",
    "nurse",
    "doctor",
    "scientist",
    "fashionista",
    "teacher",
    "CEO",
    "delivery guy",
    "model",
    "handyman",
    "farmer",
    "artist",
    "slob",
    "snob",
    "aristocrat",
    "goth",
    "himbo",
    "twink",
    "stud",
    "bear",
    "hunk",
    "muscle boy",
    "trucker",
    "gamer",
    "influencer",
    "college student",
    "dandy",
    "daddy",
    "prostitute",
    "idol",
    "mechanic",
    "cyborg",
    "elf",
    "alien",
    "mutant",
    "werewolf",
    "vampire",
    "robot",
    "construction worker",
    "captain",
    "pirate",
    "prisoner",
    "fairy",
    "cowboy",
    "poet",
    "jailor",
    "ruler",
    "soldier",
    "virgin",
    "pervert",
    "barbarian",
    "law enforcer",
    "waiter",
    "bar tender",
    "parent",
    "office worker",
    "giant",
    "spirit",
    "maid",
    "student",
    "lord",
    "prince",
    "hunter",
    "witcher",
    "magician",
    "merman",
    "angel",
    "incubus",
    "priest",
    "attorney",
    "spy",
    "assassin",
    "woodworker",
    "youtuber"
];

let wordList3 = [
    "sounding",
    "cuckolding",
    "breath play",
    "temperature play",
    "watersports",
    "bondage",
    "sensory depriviation",
    "toys",
    "voyeurism",
    "bottoming",
    "topping",
    "dominance",
    "submission",
    "feet",
    "oral sex",
    "pain",
    "flogging",
    "spanking",
    "mirror sex",
    "monsters",
    "supernatural beings",
    "underwear",
    "leather",
    "latex",
    "lingerie",
    "stockings",
    "anal sex",
    "fisting",
    "inflation",
    "tentacles",
    "exhibitionism",
    "rape",
    "role play",
    "high heels",
    "baby play",
    "pet play",
    "food play",
    "cosplay",
    "robots",
    "BDSM",
    "orgasm denial",
    "edging",
    "piercings",
    "uniforms",
    "sploshing",
    "trees",
    "armpits",
    "anonymous sex",
    "larger beings",
    "small beings",
    "biting",
    "vampires",
    "age play",
    "medical play",
    "clothed sex",
    "cross-dressing",
    "crying",
    "double penetration",
    "impact play",
    "caning",
    "tickling",
    "zentai",
    "sensation play",
    "blindfolds",
    "choking",
    "gags",
    "orgasm control",
    "discipline",
    "begging",
    "non-humans",
    "large chests",
    "muscles",
    "sweat",
    "firm butts",
    "squirting",
    "historical play",
    "foreign cultures",
    "ball play",
    "electro stimulation",
    "vibrators",
    "dildos",
    "body paint",
    "inanimate objects",
    "sleeping beauties",
    "prostate stimulation",
    "belly bulges",
    "thickness",
    "forced orgasms",
    "overstimulation",
    "machines",
    "power play",
    "body hair",
    "chastity",
    "cuddling",
    "feathers",
    "prostitution",
    "vanilla sex"
];

let wordList4 = [
    "alone",
    "with a partner",
    "in a threesome",
    "with a bunch of people",
    "with a clown",
    "with their childhood bully",
    "with their best friend",
    "with their childhood friend",
    "with their soulmate",
    "with their 5th grade english teacher",
    "with a celebrity",
    "all by themselves",
    "just for themselve",
    "with their homies",
    "with a travel group",
    "with their crew", 
    "with their clan",
    "with their gang",
    "with a plushy",
    "with their imaginary friend",
    "with their master",
    "with their subordinates",
    "with their slave",
    "with their lover",
    "with their lovers",
    "with their spouse",
    "with another couple",
    "with their favorite band",
    "with their crush",
    "with some drunk strangers",
    "with a pair of strangers",
    "in a ménage à trois",
    "with their secretary",
    "with a mysterious stranger",
    "with a group of masked people",
    "with their dom",
    "with their sub",
    "with a virgin",
    "with straight guys",
    "with a quirky twink",
    "with two brawny studs",
    "with a group of fairies",
    "with a vampire lord",
    "with themselves",
    "with their step-sibling",
    "with a police officer",
    "with two armed guards",
    "in an orgy",
    "with their sworn enemy",
    "with their boys",
    "with a DILF",
    "with a group of older men",
    "with two daddies",
    "with their manservant",
    "with their travel buddies",
    "with a one night stand",
    "with a grindr date",
    "with a group of delinquents"    
]

let wordList5 = [
    "in high places",
    "in dangerous places",
    "outdoors",
    "in the summer heat",
    "in the forest",
    "in public places",
    "in the pool",
    "at the beach",
    "in the bathtub",
    "in the shower",
    "in elevators",
    "while drunk",
    "in the club",
    "in the dark",
    "in a cage",
    "in the cold",
    "in their bed",
    "in the kitchen",
    "all over the house",
    "at work",
    "in the car",
    "in public restrooms",
    "while listening to music",
    "in a dungeon",
    "in the sauna",
    "in a bath house",
    "under the covers",
    "while on vacation",
    "on the plane",
    "in front of a mirror",
    "in a motel",
    "in a jacuzzi",
    "by the fire place",
    "in public transportation",
    "in the washing saloon",
    "in sacred places",
    "while other people are watching",
    "during thunderstorms",
    "in back alleys",
    "on the rooftop",
    "in a five star hotel",
    "in the spa",
    "at the gym",
    "in the locker room",
    "in zero gravity",
    "under the cherry trees",
    "during a relaxed afternoon",
    "while watching the sunset",
    "during a party",
    "at midnight",
    "against hard and rough surfaces",
    "in a postapocalyptic world",
    "in a mystical place",
    "while performing an ancient ritual",
    "under the stars",
    "by the campfire",
    "on the floor",
    "in a room full of people",
    "against a window",
    "for everybody to see",
    "in a tiny space",
    "on a rocking boat",
    "underwater",
    "in a dumpster behind 7/11"
]

export {wordList1, wordList2, wordList3, wordList4, wordList5};
